### ISSUE TITLE
Kafka lab

### ISSUE THREAD

**Issue by aldy120** [aldy120/s3-note#47]
Kafka lab
https://catalog.us-east-1.prod.workshops.aws/workshops/c2b72b6f-666b-4596-b8bc-bafa5dcca741/en-US

Create cluster
https://docs.aws.amazon.com/msk/latest/developerguide/create-cluster.html

其實 Zookeeper 跟 Broker 都在 AWS managed VPC 。只是有開一個 ENI 放在客戶端，用類似 VPC endpoint 的方式訪問。

**Comment by aldy120** [comment]
Detect and automatically recover. Reuse the storage. Use the same the ip address of previous broker.

**Comment by aldy120** [comment]
Create default provision MSK cluster.

**Comment by aldy120** [comment]
```
sudo yum -y install java-11
wget https://archive.apache.org/dist/kafka/2.8.1/kafka_2.13-2.8.1.tgz
2.8.1
tar -xzf kafka_2.13-2.8.1.tgz

cd kafka_2.13-2.8.1/libs
wget https://github.com/aws/aws-msk-iam-auth/releases/download/v1.1.1/aws-msk-iam-auth-1.1.1-all.jar

cd kafka_2.13-2.8.1/bin
```

file `client.properties`
```
security.protocol=SASL_SSL
sasl.mechanism=AWS_MSK_IAM
sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler
```

Private endpoint in VPC
`b-3.msktutorialcluster.kk1gxx.c8.kafka.eu-west-1.amazonaws.com:9098`

Create topic `MSKTutorialTopic`
```
cd bin
kafka-topics.sh --create --bootstrap-server BootstrapServerString --command-config client.properties --replication-factor 3 --partitions 1 --topic MSKTutorialTopic
```
Created topic MSKTutorialTopic.

**Comment by aldy120** [comment]
Producer
```
<path-to-your-kafka-installation>/bin/kafka-console-producer.sh --broker-list BootstrapServerString --producer.config client.properties --topic MSKTutorialTopic
```

```
>Mon Oct  9 20:15:08 IST 2023
>Mon Oct  9 20:15:17 IST 2023
>Mon Oct  9 20:15:24 IST 2023
>Mon Oct  9 20:15:31 IST 2023
>Mon Oct  9 20:15:38 IST 2023
>

```

**Comment by aldy120** [comment]
Consumer
```
<path-to-your-kafka-installation>/bin/kafka-console-consumer.sh --bootstrap-server BootstrapServerString --consumer.config client.properties --topic MSKTutorialTopic --from-beginning
```
```
Mon Oct  9 20:15:08 IST 2023
Mon Oct  9 20:15:17 IST 2023
Mon Oct  9 20:15:24 IST 2023
Mon Oct  9 20:15:31 IST 2023
Mon Oct  9 20:15:38 IST 2023
```

**Comment by aldy120** [comment]
Client side logs

```
sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required awsDebugCreds=true;
```

https://github.com/aws/aws-msk-iam-auth?tab=readme-ov-file#finding-out-which-identity-is-being-used

**Comment by aldy120** [comment]
Client side log

`config/log4j.properties`


再加上加這個環境變數有效
```
export KAFKA_OPTS="-Dlog4j.configuration=file:/home/ec2-user/kafka_2.13-3.5.1/config/log4j.properties"
```

**Comment by aldy120** [comment]
[SASL/SCRAM authentication](https://docs.aws.amazon.com/msk/latest/developerguide/msk-password.html)


When you set up SASL/SCRAM authentication for your cluster, Amazon MSK turns on TLS encryption for all traffic between clients and brokers.
所以某些 tls port 關閉可能會 timeout?

When you associate a secret with a cluster, Amazon MSK attaches a resource policy to the secret that allows your cluster to access and read the secret values that you defined. You should not modify this resource policy. Doing so can prevent your cluster from accessing your secret.

**Comment by aldy120** [comment]
`--zookeeper` 目前新版的 kafka 已經無法使用，改用 `--bootstrap-server`。不要用文件上寫的 `--bootstrap-server` ，不用加 s 。
```
Exception in thread "main" joptsimple.UnrecognizedOptionException: zookeeper is not a recognized option
```
[] Best practices - Use latest Kafka AdminClient to avoid topic ID mismatch issue - https://docs.aws.amazon.com/msk/latest/developerguide/bestpractices.html#topic-id-mismatch

然後發現會 timeout 。

```
Error while executing topic command : Timed out waiting for a node assignment. Call: createTopics
[2023-12-28 19:31:44,304] ERROR org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: createTopics
 (kafka.admin.TopicCommand$)
```

**Comment by aldy120** [comment]
終於搞定 SASL/SCRAM

IAM 用的是 port 9098 ， SASL/SCRAM 用的是 port 9096 。

## KAFKA_OPTS
要加上環境變數 `export KAFKA_OPTS=-Djava.security.auth.login.config=users_jaas.conf` 。不然會有下面錯誤訊息。
```
Exception in thread "main" org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:551)
```
```
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:465)
```
```
[2023-12-28 23:38:47,319] ERROR Unknown error when running consumer:  (kafka.tools.ConsoleConsumer$)
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
```
## cacerts
要把 cacerts 路徑寫到設定檔。
```
cp /usr/lib/jvm/jre-11-openjdk/lib/security/cacerts tmp/kafka.client.truststore.jks
```

## `client_sasl.properties`
```
security.protocol=SASL_SSL
sasl.mechanism=SCRAM-SHA-512
ssl.truststore.location=tmp/kafka.client.truststore.jks
```

## Example commands
```
# Create topic
./kafka-topics.sh --create --bootstrap-server b-1.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096,b-3.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096,b-2.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096 --command-config client_sasl.properties --replication-factor 3 --partitions 1 --topic MSKTutorialTopic101

# Producer
./kafka-console-producer.sh --broker-list b-1.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096,b-3.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096,b-2.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096 --producer.config client_sasl.properties --topic MSKTutorialTopic101

# Consumer
./kafka-console-consumer.sh --bootstrap-server b-1.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096,b-3.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096,b-2.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096 --consumer.config client_sasl.properties --topic MSKTutorialTopic101 --from-beginning
```

**Comment by aldy120** [comment]
```
# Create topic
./kafka-topics.sh --create --bootstrap-server b-1.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096,b-3.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096,b-2.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096 --command-config client_sasl.properties --replication-factor 3 --partitions 1 --topic MSKTutorialTopic101

# Producer
./kafka-console-producer.sh --broker-list b-1.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096,b-3.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096,b-2.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096 --producer.config client_sasl.properties --topic MSKTutorialTopic101

# Consumer
./kafka-console-consumer.sh --bootstrap-server b-1.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096,b-3.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096,b-2.test2.s4j8z5.c8.kafka.eu-west-1.amazonaws.com:9096 --consumer.config client_sasl.properties --topic MSKTutorialTopic101 --from-beginning
```
